# Generated by Django 6.0 on 2026-03-03 05:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='subtitle',
        ),
        migrations.AddField(
            model_name='job',
            name='department',
            field=models.CharField(choices=[('sales_marketing', 'Sales & Marketing'), ('customer_support', 'Customer Support'), ('tech_dev', 'Technology & Development'), ('operations_mgmt', 'Operations & Management'), ('business_dev', 'Business Development'), ('field_sales', 'Field Sales')], default='tech_dev', max_length=50),
        ),
        migrations.AddField(
            model_name='job',
            name='short_description',
            field=models.CharField(default='Short description will be updated', max_length=300),
        ),
        migrations.AddField(
            model_name='job',
            name='technologies',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='experience',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='positions',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='job',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
