# Generated by Django 6.0 on 2026-03-03 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_remove_job_subtitle_job_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='department',
            field=models.CharField(choices=[('software_development', 'Software Development'), ('customer_operations', 'Customer Operations & Loyalty Lifecycle Management'), ('iot_engineering', 'IoT, SIM, & Telematics Engineering'), ('strategic_partnerships', 'Strategic Partnerships & B2B Sales'), ('business_development', 'Business Development Executives'), ('analytics_strategy', 'Analytics, Insights & Performance Strategy')], default='software_development', max_length=50),
        ),
    ]
