# Generated by Django 6.0 on 2026-03-09 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0007_plan_price_24'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='vcPlanID',
            new_name='bqPlanID',
        ),
    ]
