# Generated by Django 6.0 on 2026-03-09 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0008_rename_vcplanid_plan_bqplanid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='sim_type',
        ),
    ]
