# Generated by Django 6.0 on 2026-03-06 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('position_applied', models.CharField(choices=[('sales_marketing', 'Sales & Marketing'), ('customer_support', 'Customer Support'), ('technology_dev', 'Technology & Development'), ('operations_mgmt', 'Operations & Management'), ('business_dev', 'Business Development'), ('field_sales', 'Field Sales')], max_length=50)),
                ('resume', models.FileField(upload_to='resumes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
