# Generated by Django 6.0 on 2026-03-09 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplication',
            old_name='created_at',
            new_name='applied_at',
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='full_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='position_applied',
            field=models.CharField(max_length=200),
        ),
    ]
