# Generated by Django 6.0 on 2026-03-09 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0002_rename_created_at_jobapplication_applied_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='position_applied',
            field=models.CharField(choices=[('Software Development', 'Software Development'), ('Customer Operations & Loyalty Lifecycle Management', 'Customer Operations & Loyalty Lifecycle Management'), ('IoT, SIM, & Telematics Engineering', 'IoT, SIM, & Telematics Engineering'), ('Strategic Partnerships & B2B Sales', 'Strategic Partnerships & B2B Sales'), ('Business Development Executives', 'Business Development Executives'), ('Analytics, Insights & Performance Strategy', 'Analytics, Insights & Performance Strategy')], max_length=200),
        ),
    ]
